import nodemailer from 'nodemailer';
import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const serviceAccountPath = path.join(__dirname, '../fourth-vehicle-445812-c2-11090e52c65f.json');
const serviceAccount = JSON.parse(fs.readFileSync(serviceAccountPath, 'utf8'));
export default async function handler(req, res) {
    if (req.method === 'OPTIONS') {
        res.setHeader('Access-Control-Allow-Origin', '*');
        res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
        res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
        return res.status(200).end();
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method Not Allowed' });
    }

    // Set CORS headers for the actual POST request
    res.setHeader('Access-Control-Allow-Origin', '*');

    const { email, firstName, lastName } = req.body;

    if (!email || !firstName || !lastName) {
        return res.status(400).json({ error: 'Email, First Name, and Last Name are required' });
    }

    try {
        // --- GOOGLE SHEETS INTEGRATION ---
        if (process.env.GOOGLE_SHEET_ID) {
            try {
                // We use dynamic imports for CommonJS if needed or just normal import
                const serviceAccountAuth = new JWT({
                    // env var values here are copied from service account credentials generated by google
                    email: serviceAccount.client_email,
                    key: serviceAccount.private_key,
                    scopes: [
                        'https://www.googleapis.com/auth/spreadsheets',
                    ],
                });

                const doc = new GoogleSpreadsheet(process.env.GOOGLE_SHEET_ID, serviceAccountAuth);
                await doc.loadInfo(); // loads document properties and worksheets
                const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`

                // Append row matching the headers (assuming headers are First Name, Last Name, Email, Timestamp)
                await sheet.addRow({
                    'First Name': firstName,
                    'Last Name': lastName,
                    'Email': email,
                    'Timestamp': new Date().toISOString()
                });
                console.log(`Successfully added to Google Sheets: ${email}`);
            } catch (sheetError) {
                console.error('Error saving to Google Sheets:', sheetError);
                // We shouldn't fail the whole request if sheets fail, but we'll log it
            }
        } else {
            console.log('GOOGLE_SHEET_ID not set in .env. Skipping Google Sheets integration.');
        }

        // --- EMAIL INTEGRATION ---
        const transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST,
            port: parseInt(process.env.SMTP_PORT || '587'),
            secure: false,
            auth: {
                user: process.env.SMTP_USER,
                pass: process.env.SMTP_PASS,
            },
        });

        const timestamp = new Date().toISOString();

        // Send email logic with dynamic timestamp subject to prevent threading
        const mailOptions = {
            from: `"WinYellow Subscription" <${process.env.SMTP_USER}>`,
            to: process.env.NOTIFY_EMAIL,
            replyTo: email,
            subject: `New WinYellow Subscriber: ${firstName} ${lastName} [${timestamp}]`,
            text: `A new user has subscribed to the WinYellow email list.\n\nName: ${firstName} ${lastName}\nEmail: ${email}`,
            html: `<p>A new user has subscribed to the WinYellow email list.</p><p><strong>Name:</strong> ${firstName} ${lastName}</p><p><strong>Email:</strong> ${email}</p>`,
        };

        await transporter.sendMail(mailOptions);
        console.log(`Successfully sent subscription email for: ${email}`);

        return res.status(200).json({ message: 'Subscription successful' });
    } catch (error) {
        console.error('Error in subscription workflow:', error);
        return res.status(500).json({
            error: 'Failed to subscribe. Please try again later.',
            details: error.message || String(error)
        });
    }
}
